# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Config_settings": "01_load_config.ipynb",
         "validate_config_file": "01_load_config.ipynb",
         "Config_schema": "01_load_config.ipynb",
         "open_config_file": "01_load_config.ipynb",
         "load_configurations": "01_load_config.ipynb",
         "CONFIG_PATH": "02_ingest.ipynb",
         "CONFIG": "02_ingest.ipynb",
         "DB_Client": "02_ingest.ipynb",
         "DB": "02_ingest.ipynb",
         "replays_info": "02_ingest.ipynb",
         "REPLAY_GEN": "02_ingest.ipynb",
         "Player_data": "02_ingest.ipynb",
         "Replay_data": "02_ingest.ipynb",
         "extend_player_info": "02_ingest.ipynb",
         "get_replay_info": "02_ingest.ipynb",
         "not_replay_duplicate": "02_ingest.ipynb",
         "get_replays_data_set": "02_ingest.ipynb",
         "build_replay_info": "02_ingest.ipynb",
         "build_reaper_collections": "02_ingest.ipynb"}

modules = ["load_config.py",
           "ingest.py"]

doc_url = "https://HDavidEspinosa.github.io/sc2trainingg/"

git_url = "https://github.com/HDavidEspinosa/sc2trainingg/tree/master/"

def custom_doc_links(name): return None
